GET http://localhost:8081/singers
###

GET http://localhost:8081/singers/1
Accept: application/json
###

### adding a new singer
POST http://localhost:8081/singers
Content-Type: application/json

{
  "birthDate": "1948-06-19",
  "firstName": "Nick",
  "lastName": "Drake"
}

### notice the ID
