spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:26257/management_db
    username: root
    password:
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:postgresql://localhost:26257/defaultdb