spring.application.name=customer

crm.welcome-message=Welcome to the Pro Spring Boot 4 CRM!
crm.max-results=50

# spring.jackson.property-naming-strategy=SNAKE_CASE

# Set the root logging level
logging.level.root=INFO

# Set a specific level for our CRM package
logging.level.com.apress.crm.customer=DEBUG

# You can even set levels for Spring framework categories
logging.level.org.springframework.web=INFO

# Groups
#logging.group.crm-debug=com.apress.crm.customer,com.apress.crm.customer.repository
#logging.level.crm-debug=DEBUG