# Production Profile
spring.datasource.url=jdbc:postgresql://localhost:5432/customers
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

logging.level.org.springframework.jdbc.core.JdbcClient=INFO
logging.level.com.apress.crm=INFO
