# CockroachDB settings
spring.datasource.url=jdbc:postgresql://localhost:26257/customer_db?sslmode=disable
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.CockroachDialect
spring.jpa.hibernate.ddl-auto=create-drop

# Cache settings (in-memory)
spring.cache.type=simple