# Development Profile
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:customers
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.sql.init.mode=always

logging.level.org.springframework.jdbc.core.JdbcClient=DEBUG
logging.level.com.apress.crm=DEBUG