spring.application.name=customer
spring.profiles.active=dev

# Security - Default user for development
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN