services:
  postgres:
    image: postgres:alpine
    container_name: postgres-management
    environment:
      POSTGRES_DB: management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis-management
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5.26.0
    container_name: neo4j-management
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"