# Production Profile - MongoDB
spring.mongodb.uri=mongodb://admin:password@localhost:27017/customers?authSource=admin

# Connection Pool Settings
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.data.mongodb=INFO
logging.level.com.apress.crm=INFO